server:
  port: 2222

spring:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3000
      password:
      jedis:
        pool:
          max-active: 1024  #最大连接数
          max-wait: 20000  #连接池最大等待时间
          max-idle: 200  #最大空闲